controller_joint_names: ['', 'left_hip_joint', 'left_shoulder_joint', 'left_thigh_joint', 'left_leg_joint', 'left_wheel_joint', 'right_hip_joint', 'right_shoulder_joint', 'right_thigh_joint', 'right_leg_joint', 'right_wheel_joint', ]
